# test profile, 测试环境配置
spring:
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf8
        username: ctgae
        password: ctgae123!@#
        driver-class-name: com.mysql.jdbc.Driver